@startuml
legend top left
🗲 is a system update triggered
endlegend

start
-> Twin update;
:🗲 Update framework in progress;
if (Pull EdgeUpdater image) then (fail)
    :EdgeUpdateFailed;
    stop
endif
if (Run edgeupdater container) then (fail)
    :EdgeUpdateFailed;
    stop
endif

partition EdgeUpdater {
    :Check edgemanager container exist
    and new image present localy;
    :Remove oldedgemanager container if exist;
    :Stop edgemanager;
    if (Rename edgemanager to oldedgemanager) then (fail)
        :Start edgemanager;
        stop
    endif
    if (Create edgemanager container with new image) then (fail)
        :Rename oldegemanager to edgemanager;
        :Start edgemanager;
        stop
    endif
    if (Start edgemanager) then (fail)
        :Remove edgemanager;
        :Rename oldegemanager to edgemanager;
        :Start edgemanager;
        stop
    endif
    ->May need to check healthcheck of new edgemanager?;
    :Remove oldedgemanager container;
    stop
}
@enduml
