@startuml
legend top left
🗲 is a system telemetry
endlegend

start
-> Twin update;
:🗲 Update framework in progress;
:Pull EdgeUpdater image;
:Run edgeUpdater container;

partition EdgeUpdater {
    :Check edgemanager container exist
    and new image present localy;
    :Remove oldedgemanager container if exist;
    :Stop edgemanager;
    :Rename edgemanager to oldedgemanager;
    :Remove oldedgemanager;
    :Create edgemanager container with new image;
    :Start edgemanager;
}
@enduml
