@startuml
legend top left
🗲 is a system telemetry
endlegend

start
-> Twin update;
:🗲 Framework update in progress;
if (Pull New EdgeManager image) then (ok)
    :Remove all images whose name ends in 'edgeupdater', whatever the version;
    if (Pull EdgeUpdater image) then (ok)
        if (Run EdgeUpdater image) then (ok)
            partition EdgeUpdater {
                ' Preflight checks
                if (EdgeManager container exist and a new image is present localy) then (ok)
                    :Stop edgemanager;
                    if (Backup edgemanager database) then (ok)
                        ' If this one fails we assume there is no EM already present
                        :Remove oldedgemanager container if exists;
                        if(Rename edgemanager container to oldedgemanager) then (ok)
                            if (Create edgemanager container with the new image) then (ok)
                                if (Start edgemanager) then (ok)
                                    if(Edge Manager reaches healthy state) then (ok)
                                        ' No error handling here, we are done, it's best effort mode
                                        :Remove DB backup;
                                        :Remove oldedgemanager container;
                                        :Remove oldedgemanager image;
                                        stop
                                        note right
                                        The edge framework is up to date
                                        end note
                                    else
                                        if(rename oldedgemanager container to edgemanager) then (ok)
                                            ' No error handling here, we are done, it's best effort mode
                                            :Restore DB;
                                            :Remove DB backup;
                                            :Remove oldedgemanager container;
                                            :Remove oldedgemanager image;
                                            if(Restart Edge Manager with error as parameter) then (ok)
                                                end
                                                note right
                                                Update failed.
                                                The Edge Manager will send [🗲 Framework update failed] after its restart.
                                                end note
                                            else
                                                end
                                                note left
                                                The device is bricked.
                                                end note
                                            endif
                                        else
                                            end
                                            note left
                                            The device is bricked.
                                            end note
                                        endif
                                    endif
                                else
                                    if(rename oldedgemanager container to edgemanager (swap them)) then (ok)
                                        ' No error handling here, we are done, it's best effort mode
                                        :Restore DB;
                                        :Remove DB backup;
                                        :Remove oldedgemanager container;
                                        :Remove oldedgemanager image;
                                        if(Restart edgemanager with error as parameter) then (ok)
                                            end
                                            note right
                                            Update failed.
                                            The Edge Manager will send [🗲 Framework update failed] after its restart.
                                            end note
                                        else
                                            end
                                            note left
                                            The device is bricked.
                                            end note
                                        endif
                                    else
                                        end
                                        note left
                                        The device is bricked.
                                        end note
                                    endif
                                endif
                            else
                                if(Rename oldedgemanager container to edgemanager (swap them)) then (ok)
                                    ' No error handling here, we are done, it's best effort mode
                                    :Restore DB;
                                    :Remove DB backup;
                                    :Remove oldedgemanager container;
                                    :Remove oldedgemanager image;
                                    if(Restart edgemanager with error as parameter) then (ok)
                                        end
                                        note right
                                        Update failed.
                                        The Edge Manager will send [🗲 Framework update failed] after its restart.
                                        end note
                                    else
                                        end
                                        note left
                                        The device is bricked.
                                        end note
                                    endif
                                else
                                    end
                                    note left
                                    The device is bricked.
                                    end note
                                endif
                            endif
                        else
                            :Remove DB backup;
                            :Remove new Edge Manager image;
                            if(Restart edgemanager with error as parameter) then (ok)
                                end
                                note right
                                Update failed.
                                The Edge Manager will send [🗲 Framework update failed] after its restart.
                                end note
                            else
                                end
                                note left
                                The device is bricked.
                                end note
                            endif
                        endif
                    else
                        :Remove new Edge Manager image;
                        if(Restart edgemanager with error as parameter) then (ok)
                            end
                            note right
                            Update failed.
                            The Edge Manager will send [🗲 Framework update failed] after its restart.
                            end note
                        else
                            end
                            note left
                            The device is bricked.
                            end note
                        endif
                    endif
                else
                    :Remove new Edge Manager image;
                    if(Restart edgemanager with error as parameter) then (ok)
                        end
                        note right
                        Update failed.
                        The Edge Manager will send [🗲 Framework update failed] after its restart.
                        end note
                    else
                        end
                        note right
                        The device is bricked.
                        end note
                    endif
                endif
            }
        else
            :Remove new Edge Manager image;
            :Remove EdgeUpdater image;
            :🗲 Framework update failed;
            end
        endif
    else
        :Remove new Edge Manager image;
        :🗲 Framework update failed;
        end
    endif
else
    :🗲 Framework update failed;
    end
endif
@enduml
