@startuml
legend top left
  On transitions : trigger [guard] /action
  🗲 is a system telemetry
  ↻ means we stay in this state
  On every state entrance an update on reported twin is performed
endlegend
[*]        -down-> Stopped: twin update [new app] /🗲install in progress & compose create
[*]            --> [*]        : twin update [new app && install failed (download failes / bad twind / bad compose / ...)] /🗲install failed && clean artefacts
Stopped                       : ↻ While prob container state is dead, exited, created
Stopped        --> Starting   : twin update [desired state == running] /🗲start in progress & compose create & compose start
Stopped        --> Restarting : app exited || crashed [restart mode == always] /docker auto restart
Stopped        --> Stopped    : twin update [desired state == running && compose start failed]
Stopped        --> Removing   : twin update [app removed] /🗲uninstall in progress && compose down
Starting                      : ↻ While probe container health is starting && container state is running
Starting       --> Running    : [probe container health == healthy]
Starting       --> Unhealthy  : health check [desired state == running && probe container health == unhealthy]
Starting       --> Stopped    : twin update [desired state == stopped] /🗲stop in progress & compose stop
Running                       : ↻ While probe container health is healthty && container state is running
Running        --> Stopped    : twin update [desired state == stopped] /🗲stop in progress & compose stop
Running        --> Stopped    : probe container crashed
Running        --> Stopped    : app exit normaly
Running        --> Unhealthy  : health check [probe container health == unhealthy]
Running        --> Removing   : twin update [app removed] /🗲uninstall in progress & compose down
Unhealthy                     : ↻ While probe container health is unhealthy && container state is running
Unhealthy      --> Stopped    : twin update [desired state == stopped]
Unhealthy      --> Stopped    : probe container crashed
Unhealthy      --> Stopped    : app exit normaly
Unhealthy      --> Running    : health check [probe container health == healthy]
Unhealthy      --> Removing   : twin update [app removed] /🗲uninstall in progress & compose down
Restarting                    : ↻ While probe container state is restarting
Restarting     --> Stopped    : [state is stopped, dead, exited, created]
Restarting     --> Running    : [probe container health == healthy && state == running]
Removing       --> [*]        : [] /remove app from reported twins
@enduml
