@startuml
skinparam componentStyle uml2

[EdgeAgent] as EA [[http://www.google.com]]
setProxy )- [EA]
blobUpload )- [EA]

[EdgeManager] as EM [[http://www.google.com]]


[DeviceManager] as DM [[http://www.google.com]]
setProxy )- [DM]

[ApplicationManager] as AM [[http://www.google.com]]
setProxy )- [AM]

rectangle "Framework interface" {
[HttpServer] as HS [[http://www.google.com]]
[HS] -- blobUpload

[MqttClient] as MC [[http://www.google.com]]

}

[Logateur] as LGT [[http://www.google.com]]




@enduml
