@startuml

title "DeviceManager checkProxy"

participant DeviceManager as DM
database Storage as Stor
participant Host

[->DM: checkProxy()

DM->Stor ++: getProxy()
Stor-->DM --: proxy
DM->Host: readDockerConfiguration()

DM-->[: differentProxy
@enduml

