@startuml

title "DeviceManager checkProxy"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->DM: checkProxy()

DM->Stor ++: getProxy()
Stor-->DM --: proxy
DM->Host: readDockerConfiguration()

DM-->[: differentProxy
@enduml

