@startuml

title "DeviceManager setProxy"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

DM->Host: writeDockerConfiguration()
DM->Host: restartDocker()
Note over DM: Here, all containers will stop, EdgeManager included

@enduml

