@startuml DeviceManager start

title "DeviceManager start"

participant ApplicationManager as AM
database Storage as Stor
participant EdgeApplication as EApp
participant ComposeApplication as CA
collections ComposeService as CS
participant DockerContainer as DCont
participant DockerComposeProxy as DComp
participant DockerProxy as D


!startsub start
EM->AM ++: start()
AM-->EM --:
!endsub

