@startuml
title Reboot with already effective desired states

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

note right of EM
EdgeManager is started and bootstrapped.
In this usecase example, an application is installed and running on device.
Application state "running" is reported on Hub.
User has registered to D2C messages on EventHub.
end note
User -> Host : reboot device
deactivate EM
Host -> Host : device reboot
activate EM
Host -> EM : start EdgeManager (restart always)
activate App
Host -> App : start application (restart always)
... starting application ...
note right of EM
Begin boot processing
end note
EM -> EM : start boot process
activate EM #Orange
EM -> EM : checks EdgeManager version compatible with storage version
EM -> Stor : retrieves information of device installed applications and their saved desired status
EM -> EM : checks device installed applications and their saved desired status are effective on device
EM -> Hub : connects to Hub
Hub --> EM : receives full twin
note right of EM
The transient starting state of the application is reported
and is therefore visible from the Hub until the end of the application startup
and the report of the final running state.
This transient state cannot be hidden.
end note
EM -> Hub : send updated reported twin state starting
EM -> EM : checks device actual state equals device desired state
... starting application ...
EM -> Hub : send updated reported twin state running
note right of EM
Finish boot processing
end note
deactivate EM
deactivate EM
deactivate App
@enduml
