@startuml

title "EdgeManager start"

participant EdgeManager as EM
participant ApplicationManager as AM
participant DeviceManager as DM
participant HttpServer as Http
participant Agent as A
participant MqttClient as Mqtt
participant Broker as Broker
database Storage as Stor

== Starting Application Manager ==

EM->AM ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/start.puml&fmt=svg start()]]
...
AM-->EM --:

== Check for new proxy ==
note over EM: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/EdgeManager/checkProxy.puml&fmt=svg checkProxy()]]

== Verify current apps ==

EM->AM ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/verifyCurrentApps.puml&fmt=svg verifyCurrentApps()]]
...
AM-->EM --:

== Verify saved desired apps ==

EM->AM ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/verifySavedDesiredApps.puml&fmt=svg verifySavedDesiredApps()]]
...
AM-->EM --:

== Starting Device Manager ==

EM->DM ++: start()
DM->EM --:

== Starting Http server ==

EM->Http ++: start()
Http-->EM --:

== Starting Agent ==

EM->A ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/Agent/start.puml&fmt=svg start()]]
...
A-->EM --:

== Starting Mqtt Client ==

EM->Mqtt ++: start()
Mqtt->Stor ++: getCredential()
Stor-->Mqtt --: credential
Mqtt->Broker: connect()
Mqtt-->EM --:

@enduml
