@startuml
title "ApplicationManager applyDesired"

participant ApplicationManager as AM
database Storage as Stor
participant EdgeApplication as EApp

[->AM: applyDesired()

alt instance not present
    note over AM: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/installApp.puml&fmt=svg EdgeApp : installApp(json)]]

else desired version different than current instance version
    note over AM: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/updateApp.puml&fmt=svg updateApp()]]

else desired state different than saved desired state
    AM->EApp ++: update()
    EApp-->AM --:
    AM->Stor ++: saveApplication()
    Stor-->AM --:
    AM->EApp ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.verify.puml&fmt=svg verify()]]
    EApp-->AM --:
end

AM-->[:
@enduml
