@startuml

title "ApplicationManager"

class ApplicationManager
class EdgeApplication {
    String name
    String version
    String appId
    String instanceId
    String serviceHealthCheck
}
class AppDescription {
    String description
    String appId
}
class ComposeApplication {
    String projectName = instanceId
}
class ComposeService {
    String name
    String image
}
class DockerContainer {
    String id
    String name
}
class Volume {
    String name
    String target
}

class Status
class DesiredStatus

ApplicationManager *-- "*"EdgeApplication
ApplicationManager *-- "*"AppDescription
EdgeApplication *-- DesiredStatus
EdgeApplication *-- ComposeApplication
EdgeApplication *-- Status
EdgeApplication o-- AppDescription
ComposeApplication *-- "*" ComposeService
ComposeService *-- "*" Volume
ComposeService o-- DockerContainer
ComposeService *-- Status

@enduml
