@startuml
title ComposeApplication kill

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->CA: kill()

opt is running
CA->DComp ++: stop()
DComp-->CA --:
end

opt is instanciated
CA->DComp ++: rm()
DComp-->CA --:
end

@enduml

