@startuml
title "ComposeApplication verify"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->CA: verify()

alt desired running
    alt is not instanciated
        note over CA: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.up.puml&fmt=svg up()]]

    else is not healthy
        CA->DComp ++: start()
        DComp-->CA --:
    end
else desired stopped
    alt is not instanciated
        note over CA: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.create.puml&fmt=svg create()]]

    else is not stopped
        CA->DComp ++: stop()
        DComp-->CA --:
    end
end

CA-->[:
@enduml

