@startuml
title "ComposeApplication interpret"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->CA: interpret(compose)

CA->DComp ++: verifyCompose(compose)
DComp-->CA --: accepted
Note over DComp: can fail
CA->DComp ++: config(compose)
DComp-->CA --: compose

CA-->[: compose
@end
