@startuml
title "ComposeApplication downloadApp"

participant ComposeApplication as CA
collections ComposeService as CS
participant DockerProxy as D

[->CA: downloadApp()


loop foreach service
CA->CS ++: pull()
CS->D ++: pull()
Note over D: can fail
D-->CS --:
CS-->CA --:
end

CA-->[:
@enduml


