@startuml
title ComposeApplication kill

participant ComposeApplication as CA
participant DockerComposeProxy as DComp

[->CA: kill()
!startsub kill
opt is running
CA->DComp ++: stop()
DComp-->CA --:
end

opt is instanciated
CA->DComp ++: rm()
DComp-->CA --:
end
!endsub
@enduml

