@startuml
title "ComposeApplication create"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->CA: create()

CA->DComp ++: create()
note over DComp : up ~--remove-orphans --no-start
DComp-->CA --:

CA-->[:
@enduml


