@startuml
title "ComposeApplication up"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->CA: up()

CA->DComp ++: up()
note over DComp : up --remove-orphans
DComp-->CA --:

CA-->[:
@enduml


