@startuml
title "ComposeApplication interpret"

participant ComposeApplication as CA
participant DockerComposeProxy as DComp

[->CA: interpret(compose)

CA->DComp ++: verifyCompose(compose)
DComp-->CA --: accepted
Note over DComp: can fail
CA->DComp ++: config(compose)
DComp-->CA --: compose

CA-->[: compose
@end
