@startuml

title "ComposeApplication remove"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->CA: remove()
CA->DComp ++: stop()
DComp-->CA --:

CA->DComp ++: rm()
note over DComp: rm ~--stop ~--force
DComp-->CA --:
CA-->[:

@enduml
