@startuml
title "ComposeApplication downloadApp"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->CA: downloadApp()

loop foreach service
CA->CS ++: pull()
CS->D ++: pull()
Note over D: can fail
D-->CS --:
CS-->CA --:
end

CA-->[:
@enduml


