@startuml
title "ComposeApplication create"

participant ComposeApplication as CA
participant DockerComposeProxy as DComp

[->CA: create()


CA->DComp ++: create()
note over DComp : up ~--remove-orphans --no-start
DComp-->CA --:


CA-->[:
@enduml


