@startuml
title "ComposeApplication up"

participant ComposeApplication as CA
participant DockerComposeProxy as DComp

[->CA: up()


CA->DComp ++: up()
note over DComp : up --remove-orphans
DComp-->CA --:

CA-->[:
@enduml


