@startuml
title "ApplicationManager downloadApp"

!startsub downloadApp
participant ApplicationManager as AM
database Storage as Stor
participant EdgeApplication as EApp
participant ComposeApplication as CA
collections ComposeService as CS
participant DockerContainer as DCont
participant DockerComposeProxy as DComp
participant DockerProxy as D

AM->AM: downloadCompose(url)
Note over AM: can fail
AM->EApp ++: checkAndInterpretCompose(compose)
EApp->CA ++: checkAndInterpretCompose(compose)
CA->DComp ++: verifyCompose(compose)
DComp-->CA --: accepted
Note over DComp: can fail
CA->DComp ++: config(compose)
DComp-->CA --: compose
CA-->EApp --: compose
EApp-->AM --: compose
!endsub
@end
