@startuml
title "ApplicationManager installApp"

participant ApplicationManager as AM
database Storage as Stor
participant EdgeAppFactory as EAF
participant EdgeApplication as EApp

[->AM: installApp(json)
!startsub installApp

AM->EAF ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/EdgeAppFactory.install.puml&fmt=svg install(json)]]
EAF-->AM --: EdgeApp

AM->EApp ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.downloadApp.puml&fmt=svg downloadApp()]]
EApp-->AM --:

AM->Stor ++: saveApplication()
Stor-->AM --:

AM->EApp ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.verify.puml&fmt=svg verify()]]
EApp-->AM --:
!endsub
AM-->[: EdgeApp
@enduml
