@startuml

title "ApplicationManager start"

!startsub newEdgeApplication
participant ApplicationManager as AM
database Storage as Stor
participant EdgeApplication as EApp
participant ComposeApplication as CA
collections ComposeService as CS
participant DockerContainer as DCont
participant DockerComposeProxy as DComp
participant DockerProxy as D

AM->EApp **: new(compose)
EApp->CA **: new(compose)
CA->DComp ++: getServices()
DComp-->CA --:
loop foreach service
CA->CS **: new()
CS->DComp: subscribToEvent()
CS->DComp ++: getContainerName()
DComp-->CS --:
opt instanciated
CS->DCont **: new(containerName)
DCont->D ++: getId()
D-->DCont --:
DCont->D ++: getStatus()
D-->DCont --:
end
end
CA->CA: computeSelfStatus()
!endsub
@enduml

