@startuml
title "ApplicationManager removeApp"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->AM: removeApp()

AM->EApp ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.remove.puml&fmt=svg remove()]]
EApp-->AM --:

AM->Stor ++: removeApplication()
Stor-->AM --:

opt appId not used by other instance
    AM->Stor ++: removeDescription()
    Stor-->AM --:
end

AM-->[:
@enduml

