@startuml

title "ApplicationManager start"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->AM: start

AM->Stor ++: getInstalledApps()
Stor-->AM --: apps

loop foreach app
AM->EApp **: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.new.puml&fmt=svg new()]]
end

AM-->[:
@enduml
