@startuml
title "ApplicationManager updateApp"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->AM: updateApp()

AM->EAF ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/EdgeAppFactory.install.puml&fmt=svg install(json)]]
EAF-->AM --: EdgeApp

opt old app is running (to be defined)
    AM->EApp ++: oldApp.stop()
    EApp-->AM --:
end


AM->Stor ++: removeApplication(old)
Stor-->AM --:

AM->Stor ++: saveApplication(new)
Stor-->AM --:

note over AM, EApp
    Do not use //verif//y here.
    Docker container may be instanciated and stopped. //verify// function will call //start// or //stop//.
    But we need to call //up// or //create// in order to instanciate new container.
end note
alt desired running

    AM->EApp ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.up.puml&fmt=svg up()]]
    EApp-->AM --:
else desired stopped
    AM->EApp ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.create.puml&fmt=svg create()]]
    EApp-->AM --:
end


AM-->[:
@enduml

