@startuml
title "ApplicationManager verifySavedDesiredApps"

participant ApplicationManager as AM
database Storage as Stor
participant EdgeApplication as EApp

[->AM: verifySavedDesiredApps()

AM->Stor ++: getDesiredApps()
Stor-->AM --: desiredApps

loop foreach desired app
    note over AM: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/applyDesired.puml&fmt=svg applyDesired()]]
end

loop foreach installed app not in desired list
    AM->EApp ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.remove.puml&fmt=svg remove()]]
    EApp-->AM --:

    AM->Stor ++: removeApplication()
    Stor-->AM --:

    opt appId not used by other instance
        AM->Stor ++: removeDescription()
        Stor-->AM --:
    end
end

AM-->[:
@enduml
