@startuml
title "ApplicationManager verifyCurrentApps"

participant ApplicationManager as AM
participant EdgeApplication as EApp

[->AM : verifyCurrentApps()

loop foreach apps
AM->EApp ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/ComposeApplication.verify.puml&fmt=svg verify()]]
EApp-->AM --:
end

AM-->[:
@enduml
