@startuml
title "ApplicationManager verifyCurrentApps"

participant ApplicationManager as AM
database Storage as Stor
participant EdgeApplication as EApp
participant ComposeApplication as CA
collections ComposeService as CS
participant DockerContainer as DCont
participant DockerComposeProxy as DComp
participant DockerProxy as D

!startsub verifyCurrentApps
loop foreach apps
note over AM: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/ApplicationManager/verifyApp.puml&fmt=svg verifyApp(app)]]
end
!endsub
@enduml
