@startuml
legend top left
🗲 is a system telemetry
endlegend

start
-> Twin update;
:🗲 Update to N+1 in progress;

if (AppN+1 already known ?) then (no)
    :Download AppN+1 description;
    if (Verify Health service) then (error)
        :🗲 Update failed
        No Twin update;
        : Remove AppN+1 decription from device;
        stop
    else (ok)
        : Download AppN+1 images;
        if(Download error) then (yes)
            :🗲 Update failed
            No Twin update;
            : Remove AppN+1 description from device;
            stop
        else(no)
        endif
    endif
else(yes)
endif
: Update AppN to AppN+1;
if(Update error ?) then (no)
    :Put the application in its desired Status;
    :Update reported twin.
    instanceId is untouched
    appId is set AppN+1;
    stop
    note
        App is updated
    end note
else(yes)
    :🗲 Update failed
    No Twin update;
    :Rollback to AppN;
    stop
endif

@enduml
