@startuml
legend top left
  🗲 is a system telemetry
endlegend

start
-> Twin update (same instance id with new app id);
:🗲 update to N+1 in progress;
: Download N+1 description file;
if (error ?) then (no)
    : Check N+1 validity;
    if (error ?) then (no)
        : Save N+1 description;
        if (error ?) then (no)
            : Check Health service;
            if (error ?) then (no)
                : Download each images;
                if (error ?) then (no)
                    : Update app to N+1 (compose up);
                    if (error ?) then (no)
                        : Save app;
                        : Twin update with new app id;
                        : Remove descritpion N if necessary;
                        stop
                        note
                        App is updated
                        end note
                    else (yes)
                        : Remove app in version N+1 (compose down);
                        : Reinstall app in version N (compose up);
                        :🗲 update failed, no twin update;
                        stop
                    endif
                else (yes)
                    :🗲 update failed
                    No twin update;
                stop
                endif
            else (yes)
                    :🗲 update failed
                    No twin update;
                stop
            endif
        else (yes)
            :🗲 update failed
            No twin update;
            stop
        endif
    else (yes)
        :🗲 update failed
        No twin update;
        stop
    endif
else (yes)
    :🗲 update failed
    No twin update;
    stop
endif
@enduml