@startuml
title "Agent bootstrap"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[-->A: bootstrap()
A->Stor ++: getBootstrapInfo()
Stor-->A --: deviceID, genuineness, bootstrapURL
A->BS ++: bootstrap()
BS-->A --: connectionString
A->Stor: saveConnectionString(connectionString)
A-->[: connectionString

@enduml



