@startuml
title "Agent start"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

[->A: start()
A->Stor ++: getProxy()
Stor-->A --: proxy

A->Stor ++: getConnectionString()
Stor-->A --: connectionString

opt No connectionString

note over A : [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/Agent/bootstrap.puml&fmt=svg bootstrap()]]
end
A->Hub: connect()
A-->[:

@enduml


