@startuml
title "Agent start"

participant Agent as A
database Storage as Stor
participant Hub as Hub


A->Stor ++: getProxy()
Stor-->A --: proxy

A->Stor ++: getConnectionString()
Stor-->A --: connectionString

opt No connectionString

note over A : [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/Agent/bootstrap.puml&fmt=svg bootstrap()]]
end
A->Hub: connect()

@enduml


