@startuml
title Uninstall of application whose installation is in progress

participant "Component tests" as L2T
participant "EdgeManager" as EM
participant "Iot Hub" as IH
participant "Event Hub" as EH

L2T -> L2T : begin test initialization stages
note left : Given
L2T -> IH : request update desired install
IH -> EM : notify update desired install
activate EM
EM -> EM: acknowledge desired install
EM -> EH : send install in progress
EH --> L2T : event install in progress
note left : When
L2T -> IH : request update desired uninstall
EM -> EM : installing...
IH -> EM : notify update desired uninstall
EM -> EM : installing...
EM -> EM : compose up, acknowledge desired uninstall
EM -> EM : Writing log uninstall in progress
EM -> EM : uninstalling...
EM --> IH : update reported uninstall
deactivate EM
L2T -> EM : Check log uninstall in progress
note left : Then
L2T -> IH : Check update reported uninstall
L2T -> L2T : Check no containers, images, networks, compose
@enduml
