@startuml
title Uninstall of application whose installation is in progress

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

note left of User : Given
EM -> EM : edgemanager is started and bootstrapped
User -> Hub : request update desired install
Hub -> EM : notify update desired install
activate EM
EM -> EM: acknowledge desired install
EM -> EH : send install in progress
EH --> User : event install in progress
note left : When
User -> Hub : request update desired uninstall
EM -> EM : installing...
Hub -> EM : notify update desired uninstall
EM -> EM : installing...
EM -> EM : compose up, acknowledge desired uninstall
EM -> EM : Writing log uninstall in progress
EM -> EM : uninstalling...
EM --> Hub : update reported uninstall
deactivate EM
User -> EM : Check log uninstall in progress
note left : Then
User -> Hub : Check update reported uninstall
User -> User : Check no containers, images, networks, compose
@enduml
