@startuml
title Uninstall of application whose installation is in progress

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

User -> EH : register to D2C messages
User -> EM : edgemanager is started
activate EM
EM -> EM : edgemanager bootstraps
User -> Hub : add application to desired twin (install request)
Hub --> EM : notify desired twin update
note right of EM
Begin manage twin synchronous task
end note
EM -> EM: start installation process
activate EM #Green
EM --> Hub : send install in progress event
Hub --> EH : send install in progress event
EH --> User : event install in progress
... check inputs ...
User -> Hub : remove app from desired twin (uninstall request)
Hub --> EM : notify desired twin update
note right of EM
manage twin task already in progress,
save the new twin event
and wait for the task to become available
end note
... download images ...
EM -> EM : compose up (installation process is finished)
deactivate EM
note right of EM
Finish manage twin synchronous task
end note
note right of EM
Begin manage twin synchronous task
end note
EM -> EM : start uninstall process
activate EM #Red
EM --> Hub : send uninstall in progress event
Hub --> EH : send uninstall in progress event
... uninstall app ...
EM --> EM : remove app from reported twin
EM --> Hub : send updated reported twin
note right of EM
Finish manage twin synchronous task
end note
deactivate EM
@enduml