@startuml

title "HttpServer setProxy"

!include https://raw.githubusercontent.com/se-edge/diagrams/develop/Participants.puml

User->Http ++: setProxy()

Http->Stor ++: saveProxy()
Stor-->Http --:

Http->EM ++: [[http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/se-edge/diagrams/develop/EdgeManager/checkProxy.puml&fmt=svg checkProxy()]]
EM-->Http --:

Http-->User --:

@enduml
